apiVersion: example.com/v1alpha1
kind: Mypython
metadata:
  name: my-python-sample
spec:
  # Default values copied from <project_dir>/helm-charts/mvc-db-app/values.yaml
  frontend:
    image: quay.io/vishwajitdandage/my-app
    imagePullSecrets: []
    replicaCount: 1
    
